# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

  # Runs a single command using the runners shell
    - name: Setup the Docker 
      run: git clone git@github.com:akshay-achar/docker-setup.git && cd docker-setup && docker build . --file Dockerfile --tag my-image-name:$(date +%s) && mkdir project && mkdir mongo_dump && mkdir mysql_dump && docker-compose up -d && docker ps && docker exec -it php_apache bash && cd simple-login 

    # Runs a single command using the runners shell
    - name: Run a Composer Install
      run: composer install 

    # Runs a set of commands using the runners shell
    - name: Run a Symfony Cache Clear
      run: |
        ./bin/console cache:clear;
        ./bin/console cache:clear --env=prod
