# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Print the Current Working Directory
      run: pwd

  # Runs a single command using the runners shell
    - name: Docker Setup
      run: cd .. && git clone https://github.com/akshay-achar/docker-setup.git && cd docker-setup && docker build . --file Dockerfile --tag my-image-name:$(date +%s) && mkdir project && mkdir mongo_dump && mkdir mysql_dump && docker-compose up -d && docker ps

    - name: Copy the Project into the Docker Project Folder
      run: ls && cp -r ../simple-login docker-setup/project/

      # Runs a single command using the runners shell
    - name: Update the Parameters
      run: sh bin/git-workflow-parameters-update.sh && cat .env.local

    - name: Print the Current Working Directory in Docker
      run: docker exec php_apache sh -c "pwd"

    - name: Docker PHP Apache and Running Symfony Basic Test
      run: docker exec php_apache bash -c " cd simple-login &&  sh ./bin/git-workflow-symfony-basic.sh"


